# Generated by Django 4.2.6 on 2023-10-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
