# Generated by Django 4.2.6 on 2023-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_main', '0002_workshop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='sadness',
        ),
        migrations.AddField(
            model_name='workshop',
            name='emoji',
            field=models.CharField(choices=[('happy', '😊'), ('congrats', '🥳'), ('wink', '😆'), ('pien', '🥺'), ('hi', '👋'), ('heart', '💗'), ('lion', '🦁')], default='happy', max_length=20),
        ),
    ]
